[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/keystatic"
  to = "/.netlify/functions/keystatic"
  status = 200

[[redirects]]
  from = "/keystatic/*"
  to = "/.netlify/functions/keystatic"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404