// Auto-generated by extract_objectives.py
// DO NOT EDIT MANUALLY — regenerate from Word document

export interface ObjectivePoints {
  condition: string;
  points: number;
}

export interface SecondaryObjective {
  id: string;
  number: number;
  name: string;
  timing: string;
  description: string;
  pointsAwarded: ObjectivePoints[];
  theme?: string;
  diceRange?: string;
  gameEffects?: string;
}

export const SECONDARY_OBJECTIVES: SecondaryObjective[] = [
  {
    id: "thin-their-ranks",
    number: 1,
    name: "Thin Their Ranks",
    timing: "End of Battle Round",
    description: "Points awarded for every 10 enemy <span class=\"keyword\">Infantry</span> or <span class=\"keyword\">Beast</span> Wounds reduced this Battle Round.",
    theme: "Purge the Foe",
    diceRange: "1-2",
    pointsAwarded: [
      {
        condition: "2 for every 10 Wounds",
        points: 0,
      },
      {
        condition: "4 awarded for every 10 Battleline Wounds",
        points: 0,
      },
    ],
    gameEffects: "None.",
  },
  {
    id: "bring-it-down",
    number: 2,
    name: "Bring It Down",
    timing: "End of Battle Round",
    description: "Points awarded for each <span class=\"keyword\">Monster </span>or <span class=\"keyword\">Vehicle </span>destroyed this Battle Round.",
    theme: "Purge the Foe",
    diceRange: "3-4",
    pointsAwarded: [
      {
        condition: "3 for models up to Toughness 9",
        points: 0,
      },
      {
        condition: "6 for models with Toughness between 10-12",
        points: 0,
      },
      {
        condition: "12 for models with Toughness 13 and above",
        points: 0,
      },
    ],
    gameEffects: "None.",
  },
  {
    id: "assassination",
    number: 3,
    name: "Assassination",
    timing: "End of Battle Round",
    description: "Points awarded for every <span class=\"keyword\">Character </span>destroyed this Battle Round.",
    theme: "Purge the Foe",
    diceRange: "5-6",
    pointsAwarded: [
      {
        condition: "2 for every Character Wounds",
        points: 0,
      },
      {
        condition: "4 awarded if the Character has the Leader keyword",
        points: 0,
      },
      {
        condition: "8 awarded if Leader is the player's Warlord",
        points: 0,
      },
      {
        condition: "2 Additional Points awarded if any of the above is completed by an attack with the Precision keyword",
        points: 0,
      },
    ],
    gameEffects: "Enemy units within 6&quot; of a <span class=\"keyword\">Leader</span> destroyed in this manner reduce their Leadership characteristic by 1 until the end of the Battle Round.\nEnemy units on the battlefield when the Warlord is destroyed in this manner reduce their Leadership by 2 until the end of the Battle.",
  },
  {
    id: "counterattack",
    number: 4,
    name: "Counterattack",
    timing: "When unit finishes activation",
    description: "Destroy enemy models, or units, that either are presently in Base-to-Base Contact with another friendly unit, or were at any point during the current Battle Round.",
    theme: "Denial",
    diceRange: "1-2",
    pointsAwarded: [
      {
        condition: "2 when at least 1 enemy model is destroyed",
        points: 0,
      },
      {
        condition: "4 when an entire enemy unit is destroyed in this manner",
        points: 0,
      },
    ],
    gameEffects: "None.",
  },
  {
    id: "take-ground",
    number: 5,
    name: "Take Ground",
    timing: "End of the Battle Round",
    description: "Points awarded for each new Primary Objective Marker you control at the end of the Battle Round with no enemy units within range of that Primary Objective Marker ",
    theme: "Denial",
    diceRange: "3-4",
    pointsAwarded: [
      {
        condition: "2 for each unit that completes this objective",
        points: 0,
      },
      {
        condition: "4 for each Battleline unit that completes this objective",
        points: 0,
      },
    ],
    gameEffects: "Friendly <span class=\"keyword\">Battleline</span> units within range of Primary Objective Markers secured under this Secondary Objective increase their Leadership characteristic by 1 whilst in range of the Primary Objective Marker.",
  },
  {
    id: "defend-the-strongpoint",
    number: 6,
    name: "Defend the Strongpoint",
    timing: "End of the Battle Round",
    description: "Points awarded for each friendly unit that uses the Remain Stationary Action while controlling a Primary Objective Marker, and is still controlling that objective at the end of the Battle Round. ",
    theme: "Denial",
    diceRange: "5-6",
    pointsAwarded: [
      {
        condition: "2 for each unit that completes this objective",
        points: 0,
      },
      {
        condition: "4 for each Battleline unit that completes this objective",
        points: 0,
      },
    ],
    gameEffects: "Friendly <span class=\"keyword\">Battleline</span> units who complete this Secondary Objective increase their Leadership characteristic by 1 whilst in range of the Primary Objective Marker.",
  },
  {
    id: "sabotage",
    number: 7,
    name: "Sabotage",
    timing: "When unit finishes its Activation.",
    description: "Complete the Mission Task Action after securing a Primary Objective Marker while there are no enemy models within 6&quot; of that Primary Objective Marker.\nCan only be successfully completed once per Objective Marker. ",
    theme: "Reconnaissance",
    diceRange: "1-2",
    pointsAwarded: [
      {
        condition: "Points",
        points: 5,
      },
    ],
    gameEffects: "The Primary Objective Marker is now Sabotaged. The first time an enemy unit becomes in range of the Objective Marker, roll a D6. On a 3+, that unit suffers D3+1 Mortal Wounds.",
  },
  {
    id: "sector-recon",
    number: 8,
    name: "Sector Recon",
    timing: "End of the Battle Round",
    description: "Select 1 enemy unit and 1 friendly unit that can draw true line-of-sight to that enemy unit and complete the Mission Task Action. The friendly unit is considered to be conducting Recon on that enemy unit. If the unit you select to attempt this objective used the Remain Stationary activation, it can select an enemy unit that has the <span class=\"keyword\">Stealth</span> ability, even if the <span class=\"keyword\">Stealth</span> ability would otherwise limit that unit from making Ranged attacks at it.\nThis objective is successful if the friendly unit is successfully conducts Recon until the end of the Battle Round, but is unsuccessful if the friendly unit either:\nIs destroyed before the end of the Battle Round\nBecomes Battle Shocked before the end of the Battle Round\nYou may only attempt this Objective with a maximum of 2 friendly units per Battle Round.",
    theme: "Reconnaissance",
    diceRange: "3-4",
    pointsAwarded: [
      {
        condition: "Points",
        points: 5,
      },
    ],
    gameEffects: "Ranged attacks by other friendly units in your army that are made against the enemy unit under Recon gain the <span class=\"keyword\">Ignores Cover</span> ability.",
  },
  {
    id: "secure-the-flank",
    number: 9,
    name: "Secure the Flank",
    timing: "When unit finishes its Activation.",
    description: "Points awarded for friendly units that end their Activation wholly within 9&quot; of a battlefield edge, either in No Man&#x27;s Land, or in the enemy&#x27;s Deployment Zone.",
    theme: "Reconnaissance",
    diceRange: "5-6",
    pointsAwarded: [
      {
        condition: "2 for each unit completing this objective in No Man's Land",
        points: 0,
      },
      {
        condition: "4 for each unit completing this objective in the enemy's Deployment Zone",
        points: 0,
      },
      {
        condition: "2 Additional Points awarded to either scenario above when the unit is Battleline",
        points: 0,
      },
    ],
    gameEffects: "None.",
  },
];