// Auto-generated by extract_objectives.py
// DO NOT EDIT MANUALLY — regenerate from Word document

export interface ObjectivePoints {
  condition: string;
  points: number;
}

export interface SecondaryObjective {
  id: string;
  number: number;
  name: string;
  timing: string;
  description: string;
  pointsAwarded: ObjectivePoints[];
  gameEffects?: string;
}

export const SECONDARY_OBJECTIVES: SecondaryObjective[] = [
  {
    id: "thin-their-ranks-d6-roll-1-2",
    number: 0,
    name: "Thin Their Ranks\tD6 Roll: 1-2",
    timing: "",
    description: "Points awarded for every 10 enemy Infantry or Beast Wounds reduced this Battle Round.",
    pointsAwarded: [
      {
        condition: "Points for every",
        points: 2,
      },
      {
        condition: "Wounds",
        points: 10,
      },
      {
        condition: "Points awarded for every",
        points: 4,
      },
      {
        condition: "Battleline Wounds",
        points: 10,
      },
    ],
  },
  {
    id: "bring-it-down-d6-roll-3-4",
    number: 0,
    name: "Bring It Down\tD6 Roll: 3-4",
    timing: "",
    description: "Points awarded for each Monster or Vehicle destroyed this Battle Round.",
    pointsAwarded: [
      {
        condition: "base",
        points: 3,
      },
      {
        condition: "base",
        points: 6,
      },
      {
        condition: "Points for models with Toughness",
        points: 12,
      },
      {
        condition: "and above",
        points: 13,
      },
    ],
  },
  {
    id: "assassination-d6-roll-5-6",
    number: 0,
    name: "Assassination\tD6 Roll: 5-6",
    timing: "",
    description: "Points awarded for every Character destroyed this Battle Round.",
    pointsAwarded: [
      {
        condition: "Points for every Character Wounds",
        points: 2,
      },
      {
        condition: "Points awarded if the Character has the Leader keyword",
        points: 4,
      },
      {
        condition: "Points awarded if Leader is the player's Warlord",
        points: 8,
      },
      {
        condition: "Additional Points awarded if any of the above is completed by an attack with the Precision keyword",
        points: 2,
      },
    ],
  },
  {
    id: "counterattack-d6-roll-1-2",
    number: 0,
    name: "Counterattack\tD6 Roll: 1-2",
    timing: "",
    description: "Destroy enemy models, or units, that either are presently in Base-to-Base Contact with another friendly unit, or were at any point during the current Battle Round.",
    pointsAwarded: [
      {
        condition: "Points awarded when at least",
        points: 2,
      },
      {
        condition: "enemy model is destroyed",
        points: 1,
      },
      {
        condition: "Points awarded when an entire enemy unit is destroyed in this manner",
        points: 4,
      },
    ],
  },
  {
    id: "take-ground-d6-roll-3-4",
    number: 0,
    name: "Take Ground\tD6 Roll: 3-4",
    timing: "",
    description: "Points awarded for each new Primary Objective Marker you control at the end of the Battle Round with no enemy units within range of that Primary Objective Marker",
    pointsAwarded: [
      {
        condition: "Points awarded for each unit that completes this objective",
        points: 2,
      },
      {
        condition: "Points awarded for each Battleline unit that completes this objective",
        points: 4,
      },
    ],
  },
  {
    id: "defend-the-strongpoint-d6-roll-5-6",
    number: 0,
    name: "Defend the Strongpoint\tD6 Roll: 5-6",
    timing: "",
    description: "Points awarded for each friendly unit that uses the Remain Stationary Action while controlling a Primary Objective Marker, and is still controlling that objective at the end of the Battle Round.",
    pointsAwarded: [
      {
        condition: "Points awarded for each unit that completes this objective",
        points: 2,
      },
      {
        condition: "Points awarded for each Battleline unit that completes this objective",
        points: 4,
      },
    ],
  },
  {
    id: "sabotage-d6-roll-1-2",
    number: 0,
    name: "Sabotage\tD6 Roll: 1-2",
    timing: "",
    description: "Complete the Mission Task Action after securing a Primary Objective Marker while there are no enemy models within 6\" of that Primary Objective Marker.\nCan only be successfully completed once per Objective Marker.",
    pointsAwarded: [
      {
        condition: "base",
        points: 5,
      },
    ],
  },
  {
    id: "sector-recon-d6-roll-3-4",
    number: 0,
    name: "Sector Recon\tD6 Roll: 3-4",
    timing: "",
    description: "Select 1 enemy unit and 1 friendly unit that can draw true line-of-sight to that enemy unit and complete the Mission Task Action. The friendly unit is considered to be conducting Recon on that enemy unit. If the unit you select to attempt this objective used the Remain Stationary activation, it can select and enemy unit that has the Stealth ability, even if the Stealth ability would otherwise limit that unit from making Ranged attacks at it.\nThis objective is successful if the friendly unit is successfully conducts Recon until the end of the Battle Round, but is unsuccessful if the friendly unit either:\nIs destroyed before the end of the Battle Round\nBecomes Battle Shocked before the end of the Battle Round\nYou may only attempt with Objective with a maximum of 2 friendly units per Battle Round.",
    pointsAwarded: [
      {
        condition: "base",
        points: 5,
      },
    ],
  },
  {
    id: "secure-the-flank-d6-roll-5-6",
    number: 0,
    name: "Secure the Flank\tD6 Roll: 5-6",
    timing: "",
    description: "Points awarded for friendly units that end their Activation wholly within 9\" of a battlefield edge, either in No Man's Land, or in the enemy's Deployment Zone.",
    pointsAwarded: [
      {
        condition: "Points awarded for each unit completing this objective in No Man's Land",
        points: 2,
      },
      {
        condition: "Points awarded for each unit completing this objective in the enemy's Deployment Zone",
        points: 4,
      },
      {
        condition: "points to either scenario above in the unit is Battleline",
        points: 2,
      },
    ],
  },
];