// Auto-generated by extract_stratagems.py
// DO NOT EDIT MANUALLY — regenerate from Word document

export interface Stratagem {
  id: string;
  name: string;
  timing: string;
  description: string;
  cost: string;
  subRows?: Array<{
    effect: string;
    cost: string;
  }>;
}

export const STRATAGEMS: Stratagem[] = [
  {
    id: "new-orders-max-uses-per-battle-round-1",
    name: "New Orders\tMax Uses per Battle Round: 1",
    maxUsesPerRound: "",
    timing: "",
    description: "Select 1 Secondary Mission Objective you currently have randomly selected, discard it, and roll a D6 to select a new Secondary Mission Objective.",
    cost: "1 per Secondary Mission Objective you want to replace",
  },
  {
    id: "re-roll-max-uses-per-battle-round-3",
    name: "Re-Roll\tMax Uses per Battle Round: 3",
    maxUsesPerRound: "",
    timing: "",
    description: "Re-roll the results of that D6 roll. A maximum of 1 D6 can be rerolled for each Command Point spent.",
    cost: "1 per D6 you wish to re-roll.",
  },
  {
    id: "without-hesitation-max-uses-per-battle-round-3",
    name: "Without Hesitation\tMax Uses per Battle Round: 3",
    maxUsesPerRound: "",
    timing: "",
    description: "Increase the unit's Activation Points characteristic by 1 for this current activation.",
    cost: "1 for Battleline units\n2 for any other units",
  },
  {
    id: "insane-bravery-max-uses-per-battle-round-1",
    name: "Insane Bravery\tMax Uses per Battle Round: 1",
    maxUsesPerRound: "",
    timing: "",
    description: "Select a unit that is Battle Shocked and must take a Rally Check. That unit is no longer Battle Shocked, and increases its Leadership characteristic by 2 until the end of the end of your next Command Phase.",
    cost: "2",
  },
  {
    id: "moment-of-glory",
    name: "Moment of Glory",
    maxUsesPerRound: "",
    timing: "",
    description: "The Leader and the unit it is leading gain any number of benefits for their listed Command Point cost. These effects last until the end of your Activation.\nThis Stratagem can only be used once per Battle by each player.",
    cost: "This Stratagem's Command Point cost varies based on the specific benefit being included in this Stratagem. Any number of these benefits can be included, with players adding to the total Command Point cost of the Stratagem accordingly.\n1 Command Point - Increase the Movement characteristic of models in the unit by 1\"\n2 Command Points - Increase the Initiative characteristic of models in the unit by 2\n1 Command Point - Increase the Attacks characteristic of models in the unit by 1\n1 Command Point - Increase the Weapons Skill characteristic of models in the unit by 1\n2 Command Points - Increase the Leadership characteristic of models in the unit by 2",
  },
  {
    id: "grenades-max-uses-per-battle-round-3",
    name: "Grenades!\tMax Uses per Battle Round: 3",
    maxUsesPerRound: "",
    timing: "",
    description: "Double the number of models that can make Ranged attacks with Grenade weapons.",
    cost: "1 for every 5 models in the unit",
  },
  {
    id: "rapid-ingress-max-uses-per-battle-round-3",
    name: "Rapid Ingress\tMax Uses per Battle Round: 3",
    maxUsesPerRound: "",
    timing: "",
    description: "Select 1 unit currently in Strategic Reserves. That unit can Enter the Battlefield from Strategic Reserves.",
    cost: "1 for Battleline units.\n2 for any other units.",
  },
  {
    id: "strategic-intercept-max-uses-per-battle-round-1",
    name: "Strategic Intercept\tMax Uses per Battle Round: 1",
    maxUsesPerRound: "",
    timing: "",
    description: "Select 1 friendly unit that has not yet been Activated this Battle Round and immediately spend up to 1 of its Activation Points. If the Action you select for this Stratagem involves making an attack (i.e., Shoot, Fight, Charge and Fight) then those attacks must be directed towards the opposing player's Activated unit. The unit you Activated for this Stratagem reduces its Activation Points by 1 when it is Activated normally.",
    cost: "1 for Battleline units\n3 for any other units",
  },
  {
    id: "overwatch-max-uses-per-battle-round-1",
    name: "Overwatch\tMax Uses per Battle Round: 1",
    maxUsesPerRound: "",
    timing: "",
    description: "Select 1 friendly unit within 24\" of the enemy unit that moved and that can draw true line of sight to them, and use the Shoot Action. Only Critical Hits are considered successful Hits as part of this Shoot Action.",
    cost: "1 for a unit that has used the Remain Stationary or Hold Fast Action this Battle Round.\n2 for any other unit",
  },
  {
    id: "tank-shock-max-uses-per-battle-round-3",
    name: "Tank Shock\tMax Uses per Battle Round: 3",
    maxUsesPerRound: "",
    timing: "",
    description: "For each Vehicle or Monster model in the unit, roll a number of D6 equal to the base Strength characteristic of the model(s) (not the Strength characteristic of any Melee weapons). Each roll of a 6 inflicts 1 Mortal Wound on the enemy unit. The enemy unit must then immediately take a Battle Shock Test before resolving any further steps of the Charge and Fight Action.",
    cost: "1 for each friendly model with a Strength characteristic of 5 or less\n2 for each friendly model with a Strength characteristic of 6 to 9\n3 for each friendly model with a Strength characteristic of 10 or higher",
  },
];