// Auto-generated by extract_stratagems.py
// DO NOT EDIT MANUALLY — regenerate from Word document

export interface Stratagem {
  id: string;
  name: string;
  maxUsesPerRound?: string;
  timing: string;
  description: string;
  cost: string;
  subRows?: Array<{
    effect: string;
    cost: string;
  }>;
}

export const STRATAGEMS: Stratagem[] = [
  {
    id: "new-orders",
    name: "New Orders",
    maxUsesPerRound: "<strong>1</strong>",
    timing: "During Step your Command Phase, if randomly selecting Secondary Objectives.",
    description: "Select 1 Secondary Mission Objective you currently have randomly selected, discard it, and roll a D6 to select a new Secondary Mission Objective. ",
    cost: "<strong>1</strong> per Secondary Mission Objective you want to replace",
  },
  {
    id: "re-roll",
    name: "Re-Roll",
    maxUsesPerRound: "<strong>3</strong>",
    timing: "At any time during the Battle Round when a D6 roll needs to be made.",
    description: "Re-roll the results of that D6 roll. A maximum of 1 D6 can be rerolled for each Command Point spent.",
    cost: "<strong>1</strong> per D6 you wish to re-roll.",
  },
  {
    id: "without-hesitation",
    name: "Without Hesitation",
    maxUsesPerRound: "<strong>3</strong>",
    timing: "When you activate a unit.",
    description: "Increase the unit&#x27;s Activation Points characteristic by 1 for this current activation.",
    cost: "<strong>1</strong> for <span class=\"keyword\">Battleline</span> units\n<strong>2</strong> for any other units",
  },
  {
    id: "insane-bravery",
    name: "Insane Bravery",
    maxUsesPerRound: "<strong>1</strong>",
    timing: "During Step 1 of your Command Phase.",
    description: "Select a unit that is Battle Shocked and must take a Rally Check. That unit is no longer Battle Shocked, and increases its Leadership characteristic by 2 until the end of the end of your next Command Phase.",
    cost: "<strong>2</strong>",
  },
  {
    id: "moment-of-glory",
    name: "Moment of Glory",
    maxUsesPerRound: "This stratagem can only be used once per Battle by each player.",
    timing: "When you Activate a <span class=\"keyword\">Leader</span> unit.",
    description: "The <span class=\"keyword\">Leader</span> and the unit it is leading gain any number of benefits for their listed Command Point cost. These effects last until the end of your Activation. ",
    cost: "This Stratagem&#x27;s Command Point cost varies based on the specific benefit being included in this Stratagem. Any number of these benefits can be included, with players adding to the total Command Point cost of the Stratagem accordingly.\n<strong>1 Command Point</strong> - Increase the Movement characteristic of models in the unit by 1&quot;\n<strong>2 Command Points</strong> - Increase the Initiative characteristic of models in the unit by 2\n<strong>1 Command Point</strong> - Increase the Attacks characteristic of models in the unit by 1\n<strong>1 Command Point</strong> - Increase the Weapons Skill characteristic of models in the unit by 1\n<strong>2 Command Points</strong> - Increase the Leadership characteristic of models in the unit by 2",
  },
  {
    id: "grenades",
    name: "Grenades!",
    maxUsesPerRound: "<strong>3</strong>",
    timing: "When you use the Shoot Action with an <span class=\"keyword\">Infantry</span> unit equipped with <span class=\"keyword\">Grenade</span><span class=\"keyword\">s</span> weapons",
    description: "Double the number of models that can make Ranged attacks with <span class=\"keyword\">Grenade</span><span class=\"keyword\"> </span>weapons.",
    cost: "<strong>1</strong> for every 5 models in the unit",
  },
  {
    id: "rapid-ingress",
    name: "Rapid Ingress",
    maxUsesPerRound: "<strong>3</strong>",
    timing: "During the first Battle Round, when it is your turn to Activate a unit.",
    description: "Select 1 unit currently in Strategic Reserves. That unit can Enter the Battlefield from Strategic Reserves.",
    cost: "<strong>1</strong> for <span class=\"keyword\">Battleline</span> units.\n<strong>2</strong> for any other units.",
  },
  {
    id: "strategic-intercept",
    name: "Strategic Intercept",
    maxUsesPerRound: "<strong>1</strong>",
    timing: "Right after the opposing player declares an Action that you wish to intercept.",
    description: "Select 1 friendly unit that has not yet been Activated this Battle Round and immediately spend up to 1 of its Activation Points. If the Action you select for this Stratagem involves making an attack (i.e., Shoot, Fight, Charge and Fight) then those attacks must be directed towards the opposing player&#x27;s Activated unit. The unit you Activated for this Stratagem reduces its Activation Points by 1 when it is Activated normally.",
    cost: "<strong>1</strong> for <span class=\"keyword\">Battleline</span> units\n<strong>3</strong> for any other units",
  },
  {
    id: "overwatch",
    name: "Overwatch",
    maxUsesPerRound: "1",
    timing: "During the Battle Round, after an enemy completes 1 of the following Actions: Move, Advance, Charge and Fight, Enter the Battlefield from Strategic Reserves, Embark or Disembark from a Transport.",
    description: "Select 1 friendly unit within 24&quot; of the enemy unit that moved and that can draw true line of sight to them, and use the Shoot Action. Only Critical Hits are considered successful Hits as part of this Shoot Action.",
    cost: "<strong>1</strong> for a unit that has used the Remain Stationary or Hold Fast Action this Battle Round.\n<strong>2</strong> for any other unit",
  },
  {
    id: "tank-shock",
    name: "Tank Shock",
    maxUsesPerRound: "<strong>3</strong>",
    timing: "During the Battle Round, after a friendly <span class=\"keyword\">Monster</span>, <span class=\"keyword\">Vehicle</span> or <span class=\"keyword\">Walker</span> unit has successfully ended a Charge move within Base-to-Base Contact with at least 1 enemy model as part of a Charge and Fight Action.",
    description: "For each <span class=\"keyword\">Vehicle</span> or <span class=\"keyword\">Monster</span> model in the unit, roll a number of D6 equal to the base Strength characteristic of the model(s) (not the Strength characteristic of any Melee weapons). Each roll of a 6 inflicts 1 Mortal Wound on the enemy unit. The enemy unit must then immediately take a Battle Shock Test before resolving any further steps of the Charge and Fight Action.",
    cost: "<strong>1</strong> for each friendly model with a Strength characteristic of 5 or less\n<strong>2</strong> for each friendly model with a Strength characteristic of 6 to 9\n<strong>3</strong> for each friendly model with a Strength characteristic of 10 or higher",
  },
];